<?php

namespace ContainerMh3kgxS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RySf2TtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RySf2Tt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RySf2Tt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'empleado' => ['privates', '.errored..service_locator.RySf2Tt.App\\Entity\\RRHH\\Empleado', NULL, 'Cannot autowire service ".service_locator.RySf2Tt": it needs an instance of "App\\Entity\\RRHH\\Empleado" but this type has been excluded in "config/services.yaml".'],
        ], [
            'empleado' => 'App\\Entity\\RRHH\\Empleado',
        ]);
    }
}
