<?php

namespace ContainerMh3kgxS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZLTkaGMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZLTkaGM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZLTkaGM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\RRHH\\EmpleadoController::delete' => ['privates', '.service_locator.v0yFMj1', 'get_ServiceLocator_V0yFMj1Service', true],
            'App\\Controller\\RRHH\\EmpleadoController::edit' => ['privates', '.service_locator.v0yFMj1', 'get_ServiceLocator_V0yFMj1Service', true],
            'App\\Controller\\RRHH\\EmpleadoController::index' => ['privates', '.service_locator.Y_acB7v', 'get_ServiceLocator_YAcB7vService', true],
            'App\\Controller\\RRHH\\EmpleadoController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RRHH\\EmpleadoController::show' => ['privates', '.service_locator.RySf2Tt', 'get_ServiceLocator_RySf2TtService', true],
            'App\\Controller\\RRHH\\PuestoTrabajoController::delete' => ['privates', '.service_locator.Sf2naB0', 'get_ServiceLocator_Sf2naB0Service', true],
            'App\\Controller\\RRHH\\PuestoTrabajoController::edit' => ['privates', '.service_locator.Sf2naB0', 'get_ServiceLocator_Sf2naB0Service', true],
            'App\\Controller\\RRHH\\PuestoTrabajoController::index' => ['privates', '.service_locator.dpVwMIr', 'get_ServiceLocator_DpVwMIrService', true],
            'App\\Controller\\RRHH\\PuestoTrabajoController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RRHH\\PuestoTrabajoController::show' => ['privates', '.service_locator.ZKbIv_y', 'get_ServiceLocator_ZKbIvYService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController::home' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\RRHH\\EmpleadoController:delete' => ['privates', '.service_locator.v0yFMj1', 'get_ServiceLocator_V0yFMj1Service', true],
            'App\\Controller\\RRHH\\EmpleadoController:edit' => ['privates', '.service_locator.v0yFMj1', 'get_ServiceLocator_V0yFMj1Service', true],
            'App\\Controller\\RRHH\\EmpleadoController:index' => ['privates', '.service_locator.Y_acB7v', 'get_ServiceLocator_YAcB7vService', true],
            'App\\Controller\\RRHH\\EmpleadoController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RRHH\\EmpleadoController:show' => ['privates', '.service_locator.RySf2Tt', 'get_ServiceLocator_RySf2TtService', true],
            'App\\Controller\\RRHH\\PuestoTrabajoController:delete' => ['privates', '.service_locator.Sf2naB0', 'get_ServiceLocator_Sf2naB0Service', true],
            'App\\Controller\\RRHH\\PuestoTrabajoController:edit' => ['privates', '.service_locator.Sf2naB0', 'get_ServiceLocator_Sf2naB0Service', true],
            'App\\Controller\\RRHH\\PuestoTrabajoController:index' => ['privates', '.service_locator.dpVwMIr', 'get_ServiceLocator_DpVwMIrService', true],
            'App\\Controller\\RRHH\\PuestoTrabajoController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RRHH\\PuestoTrabajoController:show' => ['privates', '.service_locator.ZKbIv_y', 'get_ServiceLocator_ZKbIvYService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController:home' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\RRHH\\EmpleadoController::delete' => '?',
            'App\\Controller\\RRHH\\EmpleadoController::edit' => '?',
            'App\\Controller\\RRHH\\EmpleadoController::index' => '?',
            'App\\Controller\\RRHH\\EmpleadoController::new' => '?',
            'App\\Controller\\RRHH\\EmpleadoController::show' => '?',
            'App\\Controller\\RRHH\\PuestoTrabajoController::delete' => '?',
            'App\\Controller\\RRHH\\PuestoTrabajoController::edit' => '?',
            'App\\Controller\\RRHH\\PuestoTrabajoController::index' => '?',
            'App\\Controller\\RRHH\\PuestoTrabajoController::new' => '?',
            'App\\Controller\\RRHH\\PuestoTrabajoController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::home' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RRHH\\EmpleadoController:delete' => '?',
            'App\\Controller\\RRHH\\EmpleadoController:edit' => '?',
            'App\\Controller\\RRHH\\EmpleadoController:index' => '?',
            'App\\Controller\\RRHH\\EmpleadoController:new' => '?',
            'App\\Controller\\RRHH\\EmpleadoController:show' => '?',
            'App\\Controller\\RRHH\\PuestoTrabajoController:delete' => '?',
            'App\\Controller\\RRHH\\PuestoTrabajoController:edit' => '?',
            'App\\Controller\\RRHH\\PuestoTrabajoController:index' => '?',
            'App\\Controller\\RRHH\\PuestoTrabajoController:new' => '?',
            'App\\Controller\\RRHH\\PuestoTrabajoController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:home' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
