<?php

namespace ContainerMh3kgxS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZKbIvYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZKbIv_y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZKbIv_y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'puestoTrabajo' => ['privates', '.errored..service_locator.ZKbIv_y.App\\Entity\\RRHH\\PuestoTrabajo', NULL, 'Cannot autowire service ".service_locator.ZKbIv_y": it needs an instance of "App\\Entity\\RRHH\\PuestoTrabajo" but this type has been excluded in "config/services.yaml".'],
        ], [
            'puestoTrabajo' => 'App\\Entity\\RRHH\\PuestoTrabajo',
        ]);
    }
}
