<?php

namespace ContainerMh3kgxS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YAcB7vService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y_acB7v' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y_acB7v'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'empleadoRepository' => ['privates', 'App\\Repository\\RRHH\\EmpleadoRepository', 'getEmpleadoRepositoryService', true],
        ], [
            'empleadoRepository' => 'App\\Repository\\RRHH\\EmpleadoRepository',
        ]);
    }
}
