<?php

namespace ContainerMh3kgxS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpleado2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.v0yFMj1.App\Entity\RRHH\Empleado' shared service.
     *
     * @return \App\Entity\RRHH\Empleado
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.v0yFMj1": it needs an instance of "App\\Entity\\RRHH\\Empleado" but this type has been excluded in "config/services.yaml".');
    }
}
