<?php

namespace ContainerMh3kgxS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPuestoTrabajoTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\RRHH\PuestoTrabajoType' shared autowired service.
     *
     * @return \App\Form\RRHH\PuestoTrabajoType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'RRHH'.\DIRECTORY_SEPARATOR.'PuestoTrabajoType.php';

        return $container->privates['App\\Form\\RRHH\\PuestoTrabajoType'] = new \App\Form\RRHH\PuestoTrabajoType();
    }
}
