<?php

namespace ContainerNxKhUxn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPuestoTrabajoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Sf2naB0.App\Entity\RRHH\PuestoTrabajo' shared service.
     *
     * @return \App\Entity\RRHH\PuestoTrabajo
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Sf2naB0": it needs an instance of "App\\Entity\\RRHH\\PuestoTrabajo" but this type has been excluded in "config/services.yaml".');
    }
}
