<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNeANtkE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNeANtkE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNeANtkE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNeANtkE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNeANtkE\App_KernelDevDebugContainer([
    'container.build_hash' => 'NeANtkE',
    'container.build_id' => '2fc95c0e',
    'container.build_time' => 1755125847,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNeANtkE');
