<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI5VH0J1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI5VH0J1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI5VH0J1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI5VH0J1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI5VH0J1\App_KernelDevDebugContainer([
    'container.build_hash' => 'I5VH0J1',
    'container.build_id' => 'e2ad10fa',
    'container.build_time' => 1751583311,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI5VH0J1');
