<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKT0AA6N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKT0AA6N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKT0AA6N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKT0AA6N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKT0AA6N\App_KernelDevDebugContainer([
    'container.build_hash' => 'KT0AA6N',
    'container.build_id' => '25b81f5e',
    'container.build_time' => 1750948340,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKT0AA6N');
